server:
  port: 8080

spring:
  application:
    name: myself

  freemarker:
    # 模板文件前缀（默认：classpath:/templates/）
    prefix: classpath:/templates/
    # 模板文件后缀（默认：.ftl）
    suffix: .ftl
    # 是否启用缓存（开发阶段建议设为 false，避免修改后不生效）
    cache: false
    # 模板编码（默认：UTF-8）
    charset: UTF-8
    # 内容类型（默认：text/html;charset=UTF-8）
    content-type: text/html;charset=UTF-8
    # 模板加载超时时间（毫秒，默认：5000）
    template-loader-path: classpath:/templates/  # 可自定义模板路径（多个用逗号分隔）